name: pa_the_tasklist
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  get: ^4.6.5
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  animated_theme_switcher: ^2.0.1-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
